// import type { Metadata } from "next";
// import Navbar from "@/components/Navbar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">

//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//           <Navbar />
//           {children}

//         </body>

//     </html>
//   );
// }
import Navbar from "@/components/Navbar";

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return <div className="flex flex-col min-h-screen">{children}</div>;
}
